### ISSUE TITLE
方差计算是否正确？

### ISSUE THREAD

**Issue by juli25** [YuyuZha0/bayes-smoothing#2]
在计算Beta分布的初始参数时，类BayesSmoothingExecutor的getInitialValue方法调用了getVar方法来计算方差。
这里的传入参数和方差计算公式是否有误？

double ctrVar = getVar(ctr2Sum, ctr2Sum, len);

private static double getVar(double sxx, double sx, int n) {
    return (sxx - sx * sx / n) / (n - 1);
  }

**Comment by YuyuZha0** [comment]
检查了一下发现确实有问题，应该是简单笔误，感谢指出！修改已提交。
